// <auto-generated />
using System;
using FinancasPessoais.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinancasPessoais.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a7dd7d1-0fc2-4606-8ed2-5a32311e321e"),
                            AccountNumber = "278499",
                            BankBranch = "5611",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 588, DateTimeKind.Local).AddTicks(9308),
                            Name = "Itaú"
                        },
                        new
                        {
                            Id = new Guid("a9d03220-ddea-45a0-bf2b-be3075b3c7c0"),
                            AccountNumber = "000007181",
                            BankBranch = "0081",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 592, DateTimeKind.Local).AddTicks(8580),
                            Name = "Caixa"
                        });
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.AccountPayable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("AccountsPayable");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e1430da-a3a8-4c0a-a9d6-bc7057ec52f7"),
                            Code = "R1",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 595, DateTimeKind.Local).AddTicks(2711),
                            Description = "Salário",
                            Name = "Salário",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a6611ff8-9866-486d-a13c-3b816e3a5d19"),
                            Code = "R2",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 595, DateTimeKind.Local).AddTicks(6508),
                            Description = "Serviços",
                            Name = "Serviços",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("af5c3c93-9724-49ed-97cb-e8a385eedaae"),
                            Code = "R3",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 595, DateTimeKind.Local).AddTicks(6536),
                            Description = "Empréstimo - Recebimento",
                            Name = "Empréstimo - Recebimento",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("effe2b1f-b5fc-4ce3-8306-084e7759d20c"),
                            Code = "R4",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 595, DateTimeKind.Local).AddTicks(6546),
                            Description = "Outras Receitas",
                            Name = "Outras Receitas",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("0e3d619d-9e30-4de1-a43a-82aca124e259"),
                            Code = "A1",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 595, DateTimeKind.Local).AddTicks(6554),
                            Description = "Alimentação",
                            Name = "Alimentação",
                            Type = 1
                        });
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CardLimit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceClosingDate")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceDueDate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cbaba53b-a642-4904-ad7e-542ef52c2ec0"),
                            CardLimit = 15000m,
                            CardName = "Itaucard Click Final 9289",
                            CardNumber = "5316805324229289",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 604, DateTimeKind.Local).AddTicks(4426),
                            InvoiceClosingDate = 2,
                            InvoiceDueDate = 9
                        });
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.FinancialRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreditCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PurchaseInInstallmentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("PurchaseInInstallmentsId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("FinancialReleases");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.PurchaseInInstallments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchaseValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("PurchaseInInstallments");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63ad1c50-68b8-4edd-9e38-5da54ce746bf"),
                            CategoryId = new Guid("1e1430da-a3a8-4c0a-a9d6-bc7057ec52f7"),
                            Code = "R1001",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 598, DateTimeKind.Local).AddTicks(7096),
                            Description = "Salário",
                            Name = "Salário"
                        },
                        new
                        {
                            Id = new Guid("656b9e6e-ccb2-4ec4-aec7-260e12e77091"),
                            CategoryId = new Guid("1e1430da-a3a8-4c0a-a9d6-bc7057ec52f7"),
                            Code = "R1002",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(297),
                            Description = "13º salário",
                            Name = "13º salário"
                        },
                        new
                        {
                            Id = new Guid("89862987-61fb-404c-83df-c345250260bb"),
                            CategoryId = new Guid("a6611ff8-9866-486d-a13c-3b816e3a5d19"),
                            Code = "R2001",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(323),
                            Description = "Mão-de-obra",
                            Name = "Mão-de-obra"
                        },
                        new
                        {
                            Id = new Guid("c294b7d4-16fa-4f48-8acb-07f4ffb228b2"),
                            CategoryId = new Guid("a6611ff8-9866-486d-a13c-3b816e3a5d19"),
                            Code = "R2002",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(333),
                            Description = "Venda de peças",
                            Name = "Venda de peças"
                        },
                        new
                        {
                            Id = new Guid("e098c0de-4220-4dc6-b9e6-1817a7e17323"),
                            CategoryId = new Guid("a6611ff8-9866-486d-a13c-3b816e3a5d19"),
                            Code = "R2003",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(347),
                            Description = "Revenda de peças",
                            Name = "Revenda de peças"
                        },
                        new
                        {
                            Id = new Guid("b83d0254-2036-4f58-b337-24975934ac18"),
                            CategoryId = new Guid("af5c3c93-9724-49ed-97cb-e8a385eedaae"),
                            Code = "R3001",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(438),
                            Description = "Empréstimo - Recebimento",
                            Name = "Empréstimo - Recebimento"
                        },
                        new
                        {
                            Id = new Guid("1ce0f441-1361-467f-ad6a-d30a524b5aca"),
                            CategoryId = new Guid("effe2b1f-b5fc-4ce3-8306-084e7759d20c"),
                            Code = "R4001",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(447),
                            Description = "Proventos de investimentos",
                            Name = "Proventos de investimentos"
                        },
                        new
                        {
                            Id = new Guid("c92fd019-17dc-4a7d-8d63-58f7f9fee606"),
                            CategoryId = new Guid("effe2b1f-b5fc-4ce3-8306-084e7759d20c"),
                            Code = "R4002",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(456),
                            Description = "Transferência entre contas",
                            Name = "Transferência entre contas"
                        },
                        new
                        {
                            Id = new Guid("c9c571d3-7d03-44f8-aa86-c9d064edc056"),
                            CategoryId = new Guid("0e3d619d-9e30-4de1-a43a-82aca124e259"),
                            Code = "A1001",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(468),
                            Description = "Compra em supermercado",
                            Name = "Compra em supermercado"
                        },
                        new
                        {
                            Id = new Guid("900611ec-7d08-403a-8b52-637a6149cb76"),
                            CategoryId = new Guid("0e3d619d-9e30-4de1-a43a-82aca124e259"),
                            Code = "A1002",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(477),
                            Description = "Feira: frutas e verduras",
                            Name = "Feira: frutas e verduras"
                        },
                        new
                        {
                            Id = new Guid("ccc4f160-37fb-41bc-9147-191793c0a03e"),
                            CategoryId = new Guid("0e3d619d-9e30-4de1-a43a-82aca124e259"),
                            Code = "A1003",
                            CreationDate = new DateTime(2026, 3, 1, 21, 13, 46, 599, DateTimeKind.Local).AddTicks(486),
                            Description = "Padaria",
                            Name = "Padaria"
                        });
                });

            modelBuilder.Entity("FinancasPessoais.Infra.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.AccountPayable", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("AccountsPayable")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.FinancialRelease", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Account", "Account")
                        .WithMany("FinancialReleases")
                        .HasForeignKey("AccountId");

                    b.HasOne("FinancasPessoais.Domain.Entities.CreditCard", "CreditCard")
                        .WithMany("FinancialReleases")
                        .HasForeignKey("CreditCardId");

                    b.HasOne("FinancasPessoais.Domain.Entities.PurchaseInInstallments", "PurchaseInInstallments")
                        .WithMany("FinancialReleases")
                        .HasForeignKey("PurchaseInInstallmentsId");

                    b.HasOne("FinancasPessoais.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("FinancialReleases")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("CreditCard");

                    b.Navigation("PurchaseInInstallments");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.PurchaseInInstallments", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.CreditCard", "CreditCard")
                        .WithMany("PurchaseInInstallments")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("PurchaseInInstallments")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Subcategory", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FinancasPessoais.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FinancasPessoais.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FinancasPessoais.Infra.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Account", b =>
                {
                    b.Navigation("FinancialReleases");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.CreditCard", b =>
                {
                    b.Navigation("FinancialReleases");

                    b.Navigation("PurchaseInInstallments");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.PurchaseInInstallments", b =>
                {
                    b.Navigation("FinancialReleases");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Subcategory", b =>
                {
                    b.Navigation("AccountsPayable");

                    b.Navigation("FinancialReleases");

                    b.Navigation("PurchaseInInstallments");
                });
#pragma warning restore 612, 618
        }
    }
}
